#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=$(getApplication)

#runApplication chemkinToFoam \
#               chemkin/grimech30.dat chemkin/thermo30.dat chemkin/transportProperties \
#               constant/reactionsGRI constant/thermo.compressibleGasGRI

runApplication surfaceFeatures

runApplication blockMesh

runApplication decomposePar -copyZero

runParallel snappyHexMesh -overwrite

runApplication setFields

runParallel patchSummary

runParallel $(getApplication)

runApplication reconstructParMesh -constant -mergeTol 1e-06
runApplication reconstructPar

#------------------------------------------------------------------------------
