#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=$(getApplication)

runApplication blockMesh

runApplication rotateMesh "(0 1 0)" "(0 0 1)"

runApplication decomposePar -copyZero

runParallel $application


#------------------------------------------------------------------------------
